### ISSUE TITLE
As a participant IWLT have continuous numbers.

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/UserStories#3]
"Numbers" are refeering to the teamnumber as in "Team 23".

**Comment by florianschmidt1994** [comment]
- [ ] iOS
- [ ] Android
- [ ] Web

**Comment by florianschmidt1994** [comment]
These numbers are there. They also are displayed on the web. As the apps don't show team profiles, these numbers are not visible there. I will still close this issue, as the main task "having numbers" is fulfilled
